var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

new(function(){this.navigator=window.navigator;this.document=window.document;var g,aa=aa||{},m=this;function ba(a){a=a.split(".");for(var b=m,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}function ca(){}function n(a){a.u=function(){return a.$a?a.$a:a.$a=new a}}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function da(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function t(a,b,c){t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return t.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function u(a,b){function c(){}c.prototype=b.prototype;a.xa=b.prototype;a.prototype=new c};function ma(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function na(a){var b=[];oa(new pa,a,b);return b.join("")}function pa(){this.ua=void 0}
function oa(a,b,c){switch(typeof b){case "string":qa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==p(b)){var d=b.length;c.push("[");for(var f="",e=0;e<d;e++)c.push(f),f=b[e],oa(a,a.ua?a.ua.call(b,String(e),f):f,c),f=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),
qa(e,c),c.push(":"),oa(a,a.ua?a.ua.call(b,e,f):f,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ra={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},sa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function qa(a,b){b.push('"',a.replace(sa,function(a){if(a in ra)return ra[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return ra[a]=f+b.toString(16)}),'"')};function ta(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a}function ua(a){if(!va.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));return a}var wa=/&/g,xa=/</g,ya=/>/g,za=/\"/g,va=/[&<>\"]/;
function Aa(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(d.length,f.length),h=0;0==c&&h<e;h++){var k=d[h]||"",l=f[h]||"",F=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var w=F.exec(k)||["","",""],q=s.exec(l)||["","",""];if(0==w[0].length&&0==q[0].length)break;c=((0==w[1].length?0:parseInt(w[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==w[1].length?0:parseInt(w[1],10))>(0==q[1].length?
0:parseInt(q[1],10))?1:0)||((0==w[2].length)<(0==q[2].length)?-1:(0==w[2].length)>(0==q[2].length)?1:0)||(w[2]<q[2]?-1:w[2]>q[2]?1:0)}while(0==c)}return c}function Ba(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function Ca(a){var b=r(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};var v,Da,Ea,Fa,Ga,Ha,Ia,Ja;function x(){return m.navigator?m.navigator.userAgent:null}function Ka(){return m.navigator}Ga=Fa=Ea=Da=v=!1;var La;if(La=x()){var Ma=Ka();v=0==La.indexOf("Opera");Da=!v&&-1!=La.indexOf("MSIE");Fa=(Ea=!v&&-1!=La.indexOf("WebKit"))&&-1!=La.indexOf("Mobile");Ga=!v&&!Ea&&"Gecko"==Ma.product}var Na=v,y=Da,z=Ga,A=Ea,Oa=Fa,Pa,Qa=Ka();Pa=Qa&&Qa.platform||"";Ha=-1!=Pa.indexOf("Mac");Ia=-1!=Pa.indexOf("Win");Ja=-1!=Pa.indexOf("Linux");var Ra=!!Ka()&&-1!=(Ka().appVersion||"").indexOf("X11");
function Sa(){var a=m.document;return a?a.documentMode:void 0}var Ta;a:{var Ua="",Va;if(Na&&m.opera)var Wa=m.opera.version,Ua="function"==typeof Wa?Wa():Wa;else if(z?Va=/rv\:([^\);]+)(\)|;)/:y?Va=/MSIE\s+([^\);]+)(\)|;)/:A&&(Va=/WebKit\/(\S+)/),Va)var Xa=Va.exec(x()),Ua=Xa?Xa[1]:"";if(y){var Ya=Sa();if(Ya>parseFloat(Ua)){Ta=String(Ya);break a}}Ta=Ua}var Za={};function B(a){return Za[a]||(Za[a]=0<=Aa(Ta,a))}var $a=m.document,ab=$a&&y?Sa()||("CSS1Compat"==$a.compatMode?parseInt(Ta,10):5):void 0;function bb(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function cb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function db(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var eb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function fb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<eb.length;e++)c=eb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function gb(a){Error.captureStackTrace?Error.captureStackTrace(this,gb):this.stack=Error().stack||"";a&&(this.message=String(a))}u(gb,Error);gb.prototype.name="CustomError";function hb(a,b){b.unshift(a);gb.call(this,ta.apply(null,b));b.shift()}u(hb,gb);hb.prototype.name="AssertionError";function ib(a,b){throw new hb("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var C=Array.prototype,jb=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},kb=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=r(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function lb(a){return C.concat.apply(C,arguments)}
function mb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function nb(a,b,c){return 2>=arguments.length?C.slice.call(a,b):C.slice.call(a,b,c)};function ob(a){if("function"==typeof a.C)return a.C();if(r(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return cb(a)}function pb(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(da(a)||r(a))kb(a,b,c);else{var d;if("function"==typeof a.U)d=a.U();else if("function"!=typeof a.C)if(da(a)||r(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=db(a);else d=void 0;for(var f=ob(a),e=f.length,h=0;h<e;h++)b.call(c,f[h],d&&d[h],a)}};function qb(a,b){this.t={};this.k=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof qb?(c=a.U(),d=a.C()):(c=db(a),d=cb(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}g=qb.prototype;g.e=0;g.tb=0;g.C=function(){rb(this);for(var a=[],b=0;b<this.k.length;b++)a.push(this.t[this.k[b]]);return a};g.U=function(){rb(this);return this.k.concat()};g.S=function(a){return D(this.t,a)};
g.remove=function(a){return D(this.t,a)?(delete this.t[a],this.e--,this.tb++,this.k.length>2*this.e&&rb(this),!0):!1};function rb(a){if(a.e!=a.k.length){for(var b=0,c=0;b<a.k.length;){var d=a.k[b];D(a.t,d)&&(a.k[c++]=d);b++}a.k.length=c}if(a.e!=a.k.length){for(var f={},c=b=0;b<a.k.length;)d=a.k[b],D(f,d)||(a.k[c++]=d,f[d]=1),b++;a.k.length=c}}g.get=function(a,b){return D(this.t,a)?this.t[a]:b};g.set=function(a,b){D(this.t,a)||(this.e++,this.k.push(a),this.tb++);this.t[a]=b};g.G=function(){return new qb(this)};
function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function sb(a){return tb(a||arguments.callee.caller,[])}
function tb(a,b){var c=[];if(0<=jb(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(ub(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=ub(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(tb(a.caller,b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function ub(a){if(vb[a])return vb[a];a=String(a);if(!vb[a]){var b=/function ([^\(]+)/.exec(a);vb[a]=b?b[1]:"[Anonymous]"}return vb[a]}var vb={};function E(a,b,c,d,f){this.reset(a,b,c,d,f)}E.prototype.gc=0;E.prototype.Ia=null;E.prototype.Ha=null;var wb=0;E.prototype.reset=function(a,b,c,d,f){this.gc="number"==typeof f?f:wb++;this.sb=d||la();this.N=a;this.hb=b;this.gb=c;delete this.Ia;delete this.Ha};E.prototype.wa=function(a){this.N=a};function G(a){this.Kb=a}G.prototype.pa=null;G.prototype.N=null;G.prototype.Ca=null;G.prototype.ba=null;function H(a,b){this.name=a;this.value=b}H.prototype.toString=function(){return this.name};var xb=new H("OFF",Infinity),yb=new H("SHOUT",1200),zb=new H("SEVERE",1E3),Ab=new H("WARNING",900),Bb=new H("INFO",800),Cb=new H("CONFIG",700),Db=new H("FINE",500);g=G.prototype;g.getParent=function(){return this.pa};g.wa=function(a){this.N=a};
function Eb(a){if(a.N)return a.N;if(a.pa)return Eb(a.pa);ib("Root logger has no level set.");return null}g.log=function(a,b,c){if(a.value>=Eb(this).value)for(a=this.Eb(a,b,c),b="log:"+a.hb,m.console&&(m.console.timeStamp?m.console.timeStamp(b):m.console.markTimeline&&m.console.markTimeline(b)),m.msWriteProfilerMark&&m.msWriteProfilerMark(b),b=this;b;){c=b;var d=a;if(c.ba)for(var f=0,e=void 0;e=c.ba[f];f++)e(d);b=b.getParent()}};
g.Eb=function(a,b,c){var d=new E(a,String(b),this.Kb);if(c){d.Ia=c;var f;var e=arguments.callee.caller;try{var h;var k=ba("window.location.href");if(r(c))h={message:c,name:"Unknown error",lineNumber:"Not available",fileName:k,stack:"Not available"};else{var l,F,s=!1;try{l=c.lineNumber||c.xc||"Not available"}catch(w){l="Not available",s=!0}try{F=c.fileName||c.filename||c.sourceURL||m.$googDebugFname||k}catch(q){F="Not available",s=!0}h=!s&&c.lineNumber&&c.fileName&&c.stack?c:{message:c.message,name:c.name,
lineNumber:l,fileName:F,stack:c.stack||"Not available"}}f="Message: "+ua(h.message)+'\nUrl: <a href="view-source:'+h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+ua(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ua(sb(e)+"-> ")}catch(kd){f="Exception trying to expose exception! You win, we lose. "+kd}d.Ha=f}return d};g.info=function(a,b){this.log(Bb,a,b)};function I(a,b){a.log(Db,b,void 0)}var Fb={},Gb=null;
function Hb(){Gb||(Gb=new G(""),Fb[""]=Gb,Gb.wa(Cb))}function J(a){Hb();var b;if(!(b=Fb[a])){b=new G(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=J(a.substr(0,c));c.Ca||(c.Ca={});c.Ca[d]=b;b.pa=c;Fb[a]=b}return b};function K(){0!=Ib&&fa(this)}var Ib=0;function L(a,b){this.type=a;this.currentTarget=this.target=b}L.prototype.V=!1;L.prototype.defaultPrevented=!1;L.prototype.va=!0;L.prototype.preventDefault=function(){this.defaultPrevented=!0;this.va=!1};var Jb=0;function Kb(){}g=Kb.prototype;g.key=0;g.O=!1;g.ia=!1;g.la=function(a,b,c,d,f,e){if("function"==p(a))this.bb=!0;else if(a&&a.handleEvent&&"function"==p(a.handleEvent))this.bb=!1;else throw Error("Invalid listener argument");this.H=a;this.mb=b;this.src=c;this.type=d;this.capture=!!f;this.La=e;this.ia=!1;this.key=++Jb;this.O=!1};g.handleEvent=function(a){return this.bb?this.H.call(this.La||this.src,a):this.H.handleEvent.call(this.H,a)};var Lb=!y||y&&9<=ab,Mb=y&&!B("9");!A||B("528");z&&B("1.9b")||y&&B("8")||Na&&B("9.5")||A&&B("528");z&&!B("8")||y&&B("9");function Nb(a){Nb[" "](a);return a}Nb[" "]=ca;function Ob(a,b){a&&this.la(a,b)}u(Ob,L);g=Ob.prototype;g.target=null;g.relatedTarget=null;g.offsetX=0;g.offsetY=0;g.clientX=0;g.clientY=0;g.screenX=0;g.screenY=0;g.button=0;g.keyCode=0;g.charCode=0;g.ctrlKey=!1;g.altKey=!1;g.shiftKey=!1;g.metaKey=!1;g.bc=!1;g.Ga=null;
g.la=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(z){var f;a:{try{Nb(d.nodeName);f=!0;break a}catch(e){}f=!1}f||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=A||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=A||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.bc=Ha?a.metaKey:a.ctrlKey;this.state=a.state;this.Ga=a;a.defaultPrevented&&this.preventDefault();delete this.V};
g.preventDefault=function(){Ob.xa.preventDefault.call(this);var a=this.Ga;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Mb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Pb={},M={},N={},O={};
function P(a,b,c,d,f){if("array"==p(b)){for(var e=0;e<b.length;e++)P(a,b[e],c,d,f);return null}a:{if(!b)throw Error("Invalid event type");d=!!d;var h=M;b in h||(h[b]={e:0,m:0});h=h[b];d in h||(h[d]={e:0,m:0},h.e++);var h=h[d],e=fa(a),k;h.m++;if(h[e]){k=h[e];for(var l=0;l<k.length;l++)if(h=k[l],h.H==c&&h.La==f){if(h.O)break;k[l].ia=!1;a=k[l];break a}}else k=h[e]=[],h.e++;l=Qb();h=new Kb;h.la(c,l,a,b,d,f);h.ia=!1;l.src=a;l.H=h;k.push(h);N[e]||(N[e]=[]);N[e].push(h);a.addEventListener?a!=m&&a.Sa||a.addEventListener(b,
l,d):a.attachEvent(b in O?O[b]:O[b]="on"+b,l);a=h}b=a.key;Pb[b]=a;return b}function Qb(){var a=Rb,b=Lb?function(c){return a.call(b.src,b.H,c)}:function(c){c=a.call(b.src,b.H,c);if(!c)return c};return b}function Sb(a,b,c,d,f){if("array"==p(b))for(var e=0;e<b.length;e++)Sb(a,b[e],c,d,f);else{d=!!d;a:{e=M;if(b in e&&(e=e[b],d in e&&(e=e[d],a=fa(a),e[a]))){a=e[a];break a}a=null}if(a)for(e=0;e<a.length;e++)if(a[e].H==c&&a[e].capture==d&&a[e].La==f){Tb(a[e].key);break}}}
function Tb(a){var b=Pb[a];if(b&&!b.O){var c=b.src,d=b.type,f=b.mb,e=b.capture;c.removeEventListener?c!=m&&c.Sa||c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in O?O[d]:O[d]="on"+d,f);c=fa(c);if(N[c]){var f=N[c],h=jb(f,b);0<=h&&C.splice.call(f,h,1);0==f.length&&delete N[c]}b.O=!0;if(b=M[d][e][c])b.ib=!0,Ub(d,e,c,b);delete Pb[a]}}
function Ub(a,b,c,d){if(!d.ma&&d.ib){for(var f=0,e=0;f<d.length;f++)d[f].O?d[f].mb.src=null:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.ib=!1;0==e&&(delete M[a][b][c],M[a][b].e--,0==M[a][b].e&&(delete M[a][b],M[a].e--),0==M[a].e&&delete M[a])}}function Vb(a,b,c,d,f){var e=1;b=fa(b);if(a[b]){var h=--a.m,k=a[b];k.ma?k.ma++:k.ma=1;try{for(var l=k.length,F=0;F<l;F++){var s=k[F];s&&!s.O&&(e&=!1!==Wb(s,f))}}finally{a.m=Math.max(h,a.m),k.ma--,Ub(c,d,b,k)}}return Boolean(e)}
function Wb(a,b){a.ia&&Tb(a.key);return a.handleEvent(b)}
function Rb(a,b){if(a.O)return!0;var c=a.type,d=M;if(!(c in d))return!0;var d=d[c],f,e;if(!Lb){f=b||ba("window.event");var h=!0 in d,k=!1 in d;if(h){if(0>f.keyCode||void 0!=f.returnValue)return!0;a:{var l=!1;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(F){l=!0}if(l||void 0==f.returnValue)f.returnValue=!0}}l=new Ob;l.la(f,this);f=!0;try{if(h){for(var s=[],w=l.currentTarget;w;w=w.parentNode)s.push(w);e=d[!0];e.m=e.e;for(var q=s.length-1;!l.V&&0<=q&&e.m;q--)l.currentTarget=s[q],f&=Vb(e,s[q],c,!0,l);
if(k)for(e=d[!1],e.m=e.e,q=0;!l.V&&q<s.length&&e.m;q++)l.currentTarget=s[q],f&=Vb(e,s[q],c,!1,l)}else f=Wb(a,l)}finally{s&&(s.length=0)}return f}c=new Ob(b,this);return f=Wb(a,c)};function Xb(){K.call(this)}u(Xb,K);g=Xb.prototype;g.Sa=!0;g.kb=null;g.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){Sb(this,a,b,c,d)};
g.dispatchEvent=function(a){var b=a.type||a,c=M;if(b in c){if(r(a))a=new L(a,this);else if(a instanceof L)a.target=a.target||this;else{var d=a;a=new L(b,this);fb(a,d)}var d=1,f,c=c[b],b=!0 in c,e;if(b){f=[];for(e=this;e;e=e.kb)f.push(e);e=c[!0];e.m=e.e;for(var h=f.length-1;!a.V&&0<=h&&e.m;h--)a.currentTarget=f[h],d&=Vb(e,f[h],a.type,!0,a)&&!1!=a.va}if(!1 in c)if(e=c[!1],e.m=e.e,b)for(h=0;!a.V&&h<f.length&&e.m;h++)a.currentTarget=f[h],d&=Vb(e,f[h],a.type,!1,a)&&!1!=a.va;else for(f=this;!a.V&&f&&e.m;f=
f.kb)a.currentTarget=f,d&=Vb(e,f,a.type,!1,a)&&!1!=a.va;a=Boolean(d)}else a=!0;return a};var Q={};function Yb(){K.call(this);this.K=this.Ta=null;this.Z=!1;this.oc="*";this.Pa={syn:this.nc,cid:this.vc,ack:this.vb,pageshow:this.Cc,keyboardup:this.Ib,keyboarddown:this.Hb,iframeresize:this.ec,setuserscalable:this.ic,viewporttoobig:this.qc,browserviewrequest:this.xb,browserviewresponse:this.uc,buttonexpanded:this.zb,buttoncollapsed:this.yb,resizedone:this.Dc,orientation_change:this.Bc,zoomed:this.Ec,settitle:this.hc,inittitle:this.wc}}n(Yb);u(Yb,Xb);g=Yb.prototype;g.c=J("chatango.embed.LocalComm");
g.ga=function(a){this.Ta=a;P(window,"message",this.Rb,!1,this)};g.send=function(a,b){if(!(a in this.Pa))throw"Sending illegal command "+a;var c={};c.cmd=a;this.Z&&(c.fid=this.aa);b&&(c.payload=b);send_str=na(c);this.Ta.postMessage(send_str,this.oc)};g.Rb=function(a){a=a.Ga;if(a.data){Q.d&&this.c.info("onMsg_ "+a.data);var b;try{b=ma(a.data)}catch(c){Q.d&&console.log("Chatango: unexpected msg:"+a.data);return}this.Z&&this.aa!=b.fid||(a=b.cmd,opt_arg=b.payload?[b.payload]:[],this.Pa[a].apply(this,opt_arg))}};
g.disconnect=function(){this.Z=!1};function Zb(){this.nb=la()}var $b=new Zb;Zb.prototype.set=function(a){this.nb=a};Zb.prototype.reset=function(){this.set(la())};Zb.prototype.get=function(){return this.nb};function ac(a){this.cc=a||"";this.mc=$b}g=ac.prototype;g.qb=!0;g.kc=!0;g.jc=!0;g.rb=!1;g.lc=!1;function R(a){return 10>a?"0"+a:String(a)}function bc(a,b){var c=(a.sb-b)/1E3,d=c.toFixed(3),f=0;if(1>c)f=2;else for(;100>c;)f++,c*=10;for(;0<f--;)d=" "+d;return d}function cc(a){ac.call(this,a)}u(cc,ac);function dc(){this.dc=t(this.wb,this);this.Ka=new cc;this.Ka.qb=!1;this.ab=this.Ka.rb=!1;this.fb="";this.Bb={}}function ec(a){if(!0!=a.ab){var b;Hb();b=Gb;var c=a.dc;b.ba||(b.ba=[]);b.ba.push(c);a.ab=!0}}
dc.prototype.wb=function(a){if(!this.Bb[a.gb]){var b;b=this.Ka;var c=[];c.push(b.cc," ");if(b.qb){var d=new Date(a.sb);c.push("[",R(d.getFullYear()-2E3)+R(d.getMonth()+1)+R(d.getDate())+" "+R(d.getHours())+":"+R(d.getMinutes())+":"+R(d.getSeconds())+"."+R(Math.floor(d.getMilliseconds()/10)),"] ")}b.kc&&c.push("[",bc(a,b.mc.get()),"s] ");b.jc&&c.push("[",a.gb,"] ");b.lc&&c.push("[",a.N.name,"] ");c.push(a.hb,"\n");b.rb&&a.Ia&&c.push(a.Ha,"\n");b=c.join("");if(c=fc)switch(a.N){case yb:gc(c,"info",b);
break;case zb:gc(c,"error",b);break;case Ab:gc(c,"warn",b);break;default:gc(c,"debug",b)}else window.opera?window.opera.postError(b):this.fb+=b}};var fc=window.console;function gc(a,b,c){if(a[b])a[b](c);else a.log(c)};function S(a,b){L.call(this,a);this.type=a;this.data=b}u(S,L);function hc(){Yb.call(this)}n(hc);u(hc,Yb);g=hc.prototype;g.c=J("chatango.embed.LocalCommParent");g.ga=function(a,b,c,d){hc.xa.ga.call(this,a);this.K=b;this.aa=c;this.$=d};
g.nc=function(){if(!this.Z){var a={};a.fid=this.aa;a.cid=this.K;a.height=this.$.Cb;a.width=this.$.Db;a.loc=window.location.href;a.window={width:window.innerWidth,height:window.innerHeight};a.handle=this.$.i.handle;a.styles=this.$.i.styles;a.expandedButton=!0==this.$.Va;Q.d&&this.c.info("syn received, sending cid "+this.K+" to a child");this.send("cid",a)}};g.yb=function(){this.dispatchEvent(new S("buttoncollapsed"))};
g.vb=function(a){Q.d&&this.c.info("ackRcvd for "+a);a==this.aa&&(Q.d&&this.c.info("connection established for cid "+this.aa),this.Z=!0,this.dispatchEvent(new S("connestablished")))};g.Ib=function(){var a=ic();a&&(a.style.display="none")};g.Hb=function(){var a=ic();a&&(a.style.display="block")};g.zb=function(){this.dispatchEvent(new S("buttonexpanded"))};g.ec=function(a){this.dispatchEvent(new S("resizeiframe",a))};g.ic=function(a){this.dispatchEvent(new S("setuserscalable",a))};g.qc=function(){this.dispatchEvent(new S("viewporttoobig"))};
g.xb=function(){this.dispatchEvent(new S("browserviewrequest"))};g.hc=function(a){this.dispatchEvent(new S("settitle",a))};var jc=null,jc="ebulkin",kc=jc+".dev2.chattanga.com";var lc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function mc(a,b){var c;if(a instanceof mc)this.s=void 0!==b?b:a.s,nc(this,a.P),c=a.Aa,T(this),this.Aa=c,c=a.T,T(this),this.T=c,oc(this,a.fa),c=a.qa,T(this),this.qa=c,pc(this,a.A.G()),c=a.ja,T(this),this.ja=c;else if(a&&(c=String(a).match(lc))){this.s=!!b;nc(this,c[1]||"",!0);var d=c[2]||"";T(this);this.Aa=d?decodeURIComponent(d):"";d=c[3]||"";T(this);this.T=d?decodeURIComponent(d):"";oc(this,c[4]);d=c[5]||"";T(this);this.qa=d?decodeURIComponent(d):"";pc(this,c[6]||"",!0);c=c[7]||"";T(this);this.ja=
c?decodeURIComponent(c):""}else this.s=!!b,this.A=new qc(null,0,this.s)}g=mc.prototype;g.P="";g.Aa="";g.T="";g.fa=null;g.qa="";g.ja="";g.Gb=!1;g.s=!1;
g.toString=function(){var a=[],b=this.P;b&&a.push(rc(b,sc),":");if(b=this.T){a.push("//");var c=this.Aa;c&&a.push(rc(c,sc),"@");a.push(encodeURIComponent(String(b)));b=this.fa;null!=b&&a.push(":",String(b))}if(b=this.qa)this.T&&"/"!=b.charAt(0)&&a.push("https://web.archive.org/"),a.push(rc(b,"/"==b.charAt(0)?tc:uc));(b=this.A.toString())&&a.push("?",b);(b=this.ja)&&a.push("#",rc(b,vc));return a.join("")};g.G=function(){return new mc(this)};
function nc(a,b,c){T(a);a.P=c?b?decodeURIComponent(b):"":b;a.P&&(a.P=a.P.replace(/:$/,""))}function oc(a,b){T(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.fa=b}else a.fa=null}function pc(a,b,c){T(a);b instanceof qc?(a.A=b,a.A.Oa(a.s)):(c||(b=rc(b,wc)),a.A=new qc(b,0,a.s))}function T(a){if(a.Gb)throw Error("Tried to modify a read-only Uri");}g.Oa=function(a){this.s=a;this.A&&this.A.Oa(a);return this};function rc(a,b){return r(a)?encodeURI(a).replace(b,xc):null}
function xc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var sc=/[#\/\?@]/g,uc=/[\#\?:]/g,tc=/[\#\?]/g,wc=/[\#\?@]/g,vc=/#/g;function qc(a,b,c){this.q=a||null;this.s=!!c}function U(a){if(!a.h&&(a.h=new qb,a.e=0,a.q))for(var b=a.q.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=null,e=null;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=V(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}g=qc.prototype;
g.h=null;g.e=null;g.add=function(a,b){U(this);this.q=null;a=V(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.e++;return this};g.remove=function(a){U(this);a=V(this,a);return this.h.S(a)?(this.q=null,this.e-=this.h.get(a).length,this.h.remove(a)):!1};g.S=function(a){U(this);a=V(this,a);return this.h.S(a)};g.U=function(){U(this);for(var a=this.h.C(),b=this.h.U(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};
g.C=function(a){U(this);var b=[];if(a)this.S(a)&&(b=lb(b,this.h.get(V(this,a))));else{a=this.h.C();for(var c=0;c<a.length;c++)b=lb(b,a[c])}return b};g.set=function(a,b){U(this);this.q=null;a=V(this,a);this.S(a)&&(this.e-=this.h.get(a).length);this.h.set(a,[b]);this.e++;return this};g.get=function(a,b){var c=a?this.C(a):[];return 0<c.length?String(c[0]):b};
g.toString=function(){if(this.q)return this.q;if(!this.h)return"";for(var a=[],b=this.h.U(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.C(d),e=0;e<d.length;e++){var h=f;""!==d[e]&&(h+="="+encodeURIComponent(String(d[e])));a.push(h)}return this.q=a.join("&")};g.G=function(){var a=new qc;a.q=this.q;this.h&&(a.h=this.h.G(),a.e=this.e);return a};function V(a,b){var c=String(b);a.s&&(c=c.toLowerCase());return c}
g.Oa=function(a){a&&!this.s&&(U(this),this.q=null,pb(this.h,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<a.length&&(this.q=null,this.h.set(V(this,d),mb(a)),this.e+=a.length))},this));this.s=a};function yc(a){this.ta=window.location.protocol;this.Ya=window.location.hostname;a&&(a=a instanceof mc?a.G():new mc(a,void 0),this.ta=a.P,this.Ya=a.T);env=zc(this);env==Ac?(this.ya=this.v="chatango.com",this.sa=Bc,this.oa=Cc,this.ra=Dc):env==Ec?(this.ya=this.v="chattanga.com",this.sa=this.fa=Fc,this.oa=Gc,this.ra=Hc):env==Ic?(this.ya=this.v=kc,this.sa=[1890],this.oa=[1892],this.ra=[1891]):Q.d&&env==Jc&&(this.ya=this.v=kc,this.sa=[1890],this.oa=[1892],this.ra=[1891])}
var Ac="live",Ec="staging",Ic="dev",Jc="local",Bc=["8080","1800"],Cc=["8080"],Dc=["8080"],Fc=["8080","1800"],Gc=["8080"],Hc=["8080"];g=yc.prototype;g.v=void 0;g.ya=void 0;g.sa=void 0;g.oa=void 0;g.ra=void 0;function zc(a){var b=Ac,c=a.Ya.split(".").reverse();2<=c.length&&("com"==c[0]&&"chattanga"==c[1])&&(b=3<=c.length&&"dev2"==c[2]?Ic:Ec);Q.d&&"file:"==a.ta&&(b=Jc);return b};function Kc(){this.t={}}n(Kc);Kc.prototype.c=J("chatango.managers.ManagerManager");function Lc(a,b){a.t.BASEDOMAIN=b}function Mc(a){var b=a.t.BASEDOMAIN;b||Q.d&&a.c.info("No manager found for key: BASEDOMAIN");return b};function Nc(){Mc(Kc.u()).ta.replace(":","")}n(Nc);Nc.prototype.fc="st";function Oc(){var a=Nc.u().fc,b="";a&&(b=".");var c=Mc(Kc.u());return(c.ta.replace(":","")||"http")+"://"+a+b+c.v};function Pc(a,b){this.width=a;this.height=b}Pc.prototype.G=function(){return new Pc(this.width,this.height)};Pc.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Pc.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};function Qc(a,b){var c;c=a.className;c=r(c)&&c.match(/\S+/g)||[];for(var d=nb(arguments,1),f=c.length+d.length,e=c,h=0;h<d.length;h++)0<=jb(e,d[h])||e.push(d[h]);a.className=c.join(" ");return c.length==f};var Rc=!y||y&&9<=ab;!z&&!y||y&&y&&9<=ab||z&&B("1.9.1");y&&B("9");function ic(){var a=document;a.querySelectorAll&&a.querySelector?a=a.querySelector(".bottombar"):(a=document,a=(a.querySelectorAll&&a.querySelector?a.querySelectorAll(".bottombar"):a.getElementsByClassName?a.getElementsByClassName("bottombar"):Sc("*","bottombar"))[0]);return a||null}
function Sc(a,b){var c=document,d=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(d||b))return c.querySelectorAll(d+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(d){for(var f={},e=0,h=0,k;k=c[h];h++)d==k.nodeName&&(f[e++]=k);f.length=e;return f}return c}c=c.getElementsByTagName(d||"*");if(b){f={};for(h=e=0;k=c[h];h++)d=k.className,"function"==typeof d.split&&0<=jb(d.split(/\s+/),b)&&(f[e++]=k);f.length=e;return f}return c}
function Tc(a,b){bb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Uc?a.setAttribute(Uc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Vc(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new Pc(a.clientWidth,a.clientHeight)}function W(a,b,c){var d=arguments,f=document,e=d[0],h=d[1];if(!Rc&&h&&(h.name||h.type)){e=["<",e];h.name&&e.push(' name="',ua(h.name),'"');if(h.type){e.push(' type="',ua(h.type),'"');var k={};fb(k,h);delete k.type;h=k}e.push(">");e=e.join("")}e=f.createElement(e);h&&(r(h)?e.className=h:"array"==p(h)?Qc.apply(null,[e].concat(h)):Tc(e,h));2<d.length&&Wc(f,e,d,2);return e}
function Wc(a,b,c,d){function f(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var e=c[d];!da(e)||ea(e)&&0<e.nodeType?f(e):kb(Xc(e)?mb(e):e,f)}}function X(a,b){Wc(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)}function Y(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function Yc(a){var b=document.body;b.insertBefore(a,b.childNodes[0]||null)}function Zc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function $c(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}
function ad(a,b){var c=[];bd(a,b,c,!1);return c}function bd(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||bd(a,b,c,d))return!0;a=a.nextSibling}return!1}function Xc(a){if(a&&"number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==p(a))return"function"==typeof a.item}return!1}function cd(a){return dd(a,function(a){return"HEAD"==a.nodeName&&!0})}function dd(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};function ed(a){K.call(this);this.W=a||window;this.Jb=P(this.W,"resize",this.Fb,!1,this);this.J=Vc(this.W||window);if(A&&Ia||Na&&this.W.self!=this.W.top)this.sc=window.setInterval(t(this.Ra,this),fd)}u(ed,Xb);var fd=500;g=ed.prototype;g.Jb=null;g.W=null;g.J=null;g.sc=null;g.L=function(){return this.J?this.J.G():null};g.Fb=function(){this.Ra()};g.Ra=function(){var a=Vc(this.W||window);a==this.J||a&&this.J&&a.width==this.J.width&&a.height==this.J.height||(this.J=a,this.dispatchEvent("resize"))};function gd(){this.rc=new ed}n(gd);function hd(){var a=x().toLowerCase();this.Ua=-1!=a.indexOf("mobile")&&-1==a.indexOf("kindle")&&-1==a.indexOf("ipad")?id:-1!=a.indexOf("android")||-1!=a.indexOf("ipad")||-1!=a.indexOf("silk")?jd:ld}n(hd);var id="mobile",jd="tablet",ld="desktop";hd.prototype.Ua="desktop";function md(){}n(md);function nd(){md.u();return"r0523141227"};function Z(a,b,c){r(b)?od(a,c,b):bb(b,ka(od,a))}function od(a,b,c){var d;a:if(d=Ba(c),void 0===a.style[d]&&(c=(A?"Webkit":z?"Moz":y?"ms":Na?"O":null)+Ca(c),void 0!==a.style[c])){d=c;break a}d&&(a.style[d]=b)};var pd=!!x().match(/\bAndroid\b/);function qd(a){var b=x().match(/\bAndroid\s+(\S+);/);return!b||2>b.length?!1:0<=Aa(b[1],a)}x().match(/\b(iOS|iPhone|iPad|iPod)\b/);function rd(){}n(rd);
rd.prototype.Da=[{type:"blank",rules:[[{styles:"jsr"},{platform:"IE",platform:"NOT_IEMOBILE",lessThan:10}],[{styles:"jsr"},{platform:"OPERA"},{features:["NOWEBSOCKET"]}],[{styles:"jsr"},{platform:"GECKO"},{features:["NOWEBSOCKET"]}],[{styles:"jsr"},{platform:"ANDROID"},{features:["NOWEBSOCKET"]}],[{styles:"jsr"},{styles:"is_cv"},{platform:"ANDROID"}],[{styles:"jsr"},{features:["NOWEBSOCKET"]}]]},{type:"jsonly",rules:[[{styles:"jsr"}]]},{type:"flash",rules:[{param:"flash"},[{param:"js"},{platform:"IE",
platform:"NOT_IEMOBILE",lessThan:10},{features:["FLASH"]}]]},{type:"linkandroidchrome",rules:[[{platform:"ANDROID",atLeast:4},{features:["NOWEBSOCKET"]}]]},{type:"linkandroidff",rules:[{param:"js",platform:"ANDROID",lessThan:4,features:["NOWEBSOCKET"]},{platform:"ANDROID",lessThan:4,features:["NOFLASH"],platform:["NOT_GECKO"]}]},{type:"linkdesktopchrome",rules:[[{param:"js"},{platform:"IE",platform:"NOT_IEMOBILE",lessThan:10},{features:["NOFLASH"]}],[{param:"js"},{platform:"OPERA"},{features:["NOWEBSOCKET"]}],
[{param:"js"},{platform:"GECKO"},{features:["NOWEBSOCKET"]}]]},{type:"js",rules:[{param:"js"},{platform:"IOS"},{platform:"IEMOBILE"},[{platform:"MOBILE"},{platform:"CHROME"}],[{platform:"ANDROID",features:["WEBSOCKET"]},{platform:"CHROME"}],[{platform:"ANDROID",features:["WEBSOCKET"]},{platform:"GECKO"}]]}];rd.prototype.c=J("chatango.settings.Architecture");
function sd(a,b,c){var d,f,e,h,k;a.lb="js"===b?"js":null;a.B=c?c:{};for(b=0;b<a.Da.length;b++)for(c=a.Da[b].type,d=a.Da[b].rules,f=0;f<d.length;f++)if(e=d[f],Q.d&&a.c.info("Testing rule: "+na(e)),"undefined"!==typeof e.length){k=!0;for(h=0;h<e.length;h++)if(!td(a,e[h])){k=!1;break}if(k)return Q.d&&a.c.info("Rule matches: "+c),c}else if(td(a,e))return Q.d&&a.c.info("Rule matches"),c;Q.d&&a.c.info("Using default architecture");return"flash"}
function ud(){try{return-1!=navigator.userAgent.indexOf("MSIE")?(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"):navigator.plugins["Shockwave Flash"].description}catch(a){return null}}
function td(a,b){Q.d&&a.c.info("Checking rule: "+na(b));var c,d=x(),f=new mc(window.location.href);Q.d&&a.c.info("Checking rule platform");if("undefined"!=typeof b.platform)if("IE"==b.platform){if(!y)return!1}else if("IEMOBILE"==b.platform){if(!/(iemobile)/i.test(d))return!1}else if("NOT_IEMOBILE"==b.platform){if(/(iemobile)/i.test(d))return!1}else if("GECKO"==b.platform){if(!z)return!1}else if("NOT_GECKO"==b.platform){if(z)return!1}else if("WEBKIT"==b.platform){if(!A)return!1}else if("CHROME"==b.platform){if(!d.match(/\bChrome\b/))return!1}else if("LINUX"==
b.platform){if(!Ja)return!1}else if("MAC"==b.platform){if(!Ha)return!1}else if("MOBILE"==b.platform){if(!Oa)return!1}else if("OPERA"==b.platform){if(!Na)return!1}else if("SAFARI"==b.platform){if(!A)return!1}else if("WINDOWS"==b.platform){if(!Ia)return!1}else if("X11"==b.platform){if(!Ra)return!1}else if("IOS"==b.platform){if(!d||!d.match(/\b(iOS|iPod|iPad|iPhone)\b/))return!1}else if(!("ANDROID"!=b.platform||d&&pd))return!1;Q.d&&a.c.info("Checking rule version");if("ANDROID"==b.platform){if("undefined"!=
typeof b.lessThan&&qd(b.lessThan)||"undefined"!=typeof b.atLeast&&!qd(b.atLeast))return!1}else if("undefined"!=typeof b.lessThan&&B(b.lessThan)||"undefined"!=typeof b.atLeast&&!B(b.atLeast))return!1;Q.d&&a.c.info("Checking rule features");if("undefined"!=typeof b.features)for(c=0;c<b.features.length;c++){if("WEBSOCKET"==b.features[c]&&"undefined"==typeof window.WebSocket)return!1;if("NOWEBSOCKET"==b.features[c]){var e=!1;pd&&!/(chrome|opera|firefox)/i.test(d)&&(e=!0);if("undefined"!=typeof window.WebSocket&&
!e)return!1}if("FLASH"==b.features[c]&&!ud()||"NOFLASH"==b.features[c]&&ud())return!1}Q.d&&a.c.info("Checking rule parameters");if("undefined"!==typeof b.param&&(Q.d&&(a.c.info('uri.getParameterValue(rule["param"]): '+f.A.get(b.param)),a.c.info('typeof uri.getParameterValue(rule["param"]): '+typeof f.A.get(b.param))),"undefined"===typeof f.A.get(b.param)&&(!a.lb||a.lb!=b.param)))return!1;Q.d&&a.c.info("Checking rule parameters");if("undefined"!==typeof b.styles)if(a.B)switch(b.styles){case "jsr":if(!(a.B.cv&&
0!=a.B.cv||a.B.pos&&"none"!=a.B.pos||a.B.mockgroup))return!1;break;case "is_cv":if(!(a.B.cv&&0!=a.B.cv||a.B.pos&&"none"!=a.B.pos))return!1}else return!1;Q.d&&a.c.info("Rule matches");return!0};function vd(){}vd.prototype.ha=null;var wd;function xd(){}u(xd,vd);function yd(a){return(a=zd(a))?new ActiveXObject(a):new XMLHttpRequest}function Ad(a){var b={};zd(a)&&(b[0]=!0,b[1]=!0);return b}
function zd(a){if(!a.Za&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Za=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Za}wd=new xd;function Bd(a){K.call(this);this.headers=new qb;this.X=a||null}u(Bd,Xb);Bd.prototype.p=J("goog.net.XhrIo");var Cd=/^https?$/i;g=Bd.prototype;g.o=!1;g.g=null;g.Ba=null;g.M="";g.eb="";g.da=0;g.ea="";g.Fa=!1;g.ka=!1;g.Na=!1;g.ca=!1;g.za=0;g.Q=null;g.ob="";g.tc=!1;
g.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.ea="";this.da=0;this.eb=b;this.Fa=!1;this.o=!0;this.g=this.Ea();this.Ba=this.X?this.X.ha||(this.X.ha=Ad(this.X)):wd.ha||(wd.ha=Ad(wd));this.g.onreadystatechange=t(this.jb,this);try{I(this.p,$(this,"Opening Xhr")),this.Na=!0,this.g.open(b,a,!0),this.Na=!1}catch(f){I(this.p,$(this,"Error opening Xhr: "+f.message));Dd(this,f);return}a=
c||"";var e=this.headers.G();d&&pb(d,function(a,b){e.set(b,a)});d=m.FormData&&a instanceof m.FormData;"POST"!=b||(e.S("Content-Type")||d)||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");pb(e,function(a,b){this.g.setRequestHeader(b,a)},this);this.ob&&(this.g.responseType=this.ob);"withCredentials"in this.g&&(this.g.withCredentials=this.tc);try{this.Q&&(m.clearTimeout(this.Q),this.Q=null),0<this.za&&(I(this.p,$(this,"Will abort after "+this.za+"ms if incomplete")),this.Q=m.setTimeout(t(this.pc,
this),this.za)),I(this.p,$(this,"Sending request")),this.ka=!0,this.g.send(a),this.ka=!1}catch(h){I(this.p,$(this,"Send error: "+h.message)),Dd(this,h)}};g.Ea=function(){return this.X?yd(this.X):yd(wd)};g.pc=function(){"undefined"!=typeof aa&&this.g&&(this.ea="Timed out after "+this.za+"ms, aborting",this.da=8,I(this.p,$(this,this.ea)),this.dispatchEvent("timeout"),this.abort(8))};function Dd(a,b){a.o=!1;a.g&&(a.ca=!0,a.g.abort(),a.ca=!1);a.ea=b;a.da=5;Ed(a);a.Y()}
function Ed(a){a.Fa||(a.Fa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}g.abort=function(a){this.g&&this.o&&(I(this.p,$(this,"Aborting")),this.o=!1,this.ca=!0,this.g.abort(),this.ca=!1,this.da=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),this.Y())};g.jb=function(){this.Na||this.ka||this.ca?Fd(this):this.Ub()};g.Ub=function(){Fd(this)};
function Fd(a){if(a.o&&"undefined"!=typeof aa)if(a.Ba[1]&&4==Gd(a)&&2==Hd(a))I(a.p,$(a,"Local request error detected and ignored"));else if(a.ka&&4==Gd(a))m.setTimeout(t(a.jb,a),0);else if(a.dispatchEvent("readystatechange"),4==Gd(a)){I(a.p,$(a,"Request complete"));a.o=!1;try{var b=Hd(a),c,d;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:d=!0;break a;default:d=!1}if(!(c=d)){var f;if(f=0===b){var e=String(a.M).match(lc)[1]||null;if(!e&&self.location)var h=self.location.protocol,
e=h.substr(0,h.length-1);f=!Cd.test(e?e.toLowerCase():"")}c=f}if(c)a.dispatchEvent("complete"),a.dispatchEvent("success");else{a.da=6;var k;try{k=2<Gd(a)?a.g.statusText:""}catch(l){I(a.p,"Can not get status: "+l.message),k=""}a.ea=k+" ["+Hd(a)+"]";Ed(a)}}finally{a.Y()}}}
g.Y=function(a){if(this.g){var b=this.g,c=this.Ba[0]?ca:null;this.Ba=this.g=null;this.Q&&(m.clearTimeout(this.Q),this.Q=null);a||this.dispatchEvent("ready");try{b.onreadystatechange=c}catch(d){this.p.log(zb,"Problem encountered resetting onreadystatechange: "+d.message,void 0)}}};function Gd(a){return a.g?a.g.readyState:0}function Hd(a){try{return 2<Gd(a)?a.g.status:-1}catch(b){return a.p.log(Ab,"Can not get status: "+b.message,void 0),-1}}g.Wa=function(){return String(this.M)};
g.Xa=function(a){if(this.g){var b=this.g.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return ma(b)}};function $(a,b){return b+" ["+a.eb+" "+a.M+" "+Hd(a)+"]"};function Id(){K.call(this);this.n=null;this.o=!1}u(Id,Xb);g=Id.prototype;g.c=J("chatango.networking.XdrIo");g.Xa=function(a){if(this.n){var b=this.n.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return ma(b)}};g.Wa=function(){return String(this.M)};
g.send=function(a,b,c){if(this.n)throw Error("[chatango.networking.XdrIo] Object is active with another request");this.M=a;b=b?b.toUpperCase():"GET";try{var d=new XDomainRequest}catch(f){throw Error("[chatango.networking.XdrIo: Unable to create XDomainRequest: "+f.message);}this.n=d;this.o=!0;this.n.onload=t(this.Qb,this);this.n.onerror=t(this.Ob,this);this.n.ontimeout=t(this.Zb,this);try{Q.d&&this.c.info("Opening Xdr"),this.n.open(b,a)}catch(e){this.c.log(Ab,"Error opening Xdr: "+e.message,void 0);
return}a=c||"";try{Q.d&&this.c.info("Sending request"),this.n.send(a)}catch(h){this.c.log(Ab,"Send error: "+h.message,void 0)}};g.Qb=function(){Q.d&&this.c.info("XDR Loaded");this.o=!1;this.pb=new ActiveXObject("Microsoft.XMLDOM");this.pb.async=!1;this.pb.loadXML(this.n.responseText);this.dispatchEvent("complete");this.dispatchEvent("success");Jd(this)};g.Ob=function(){Q.d&&this.c.info("XDR Error");this.o=!1;this.dispatchEvent("complete");this.dispatchEvent("error");Jd(this)};
g.Zb=function(){Q.d&&this.c.info("XDR Timeout");this.o=!1;this.dispatchEvent("complete");this.dispatchEvent("error");Jd(this)};g.abort=function(){this.n&&this.o&&(Q.d&&I(this.p,$(this,"Aborting")),this.o=!1,this.n.abort(),this.dispatchEvent("complete"),this.dispatchEvent("abort"),Jd(this))};function Jd(a){var b=a.n;a.n=null;b.zc=null;b.yc=null;b.Ac=null};function Kd(a,b){this.Qa=!0===b;Bd.call(this,a)}u(Kd,Bd);Kd.prototype.Ea=function(){var a=Kd.xa.Ea.call(this);this.Qa&&P(a.upload,"progress",this.dispatchEvent,!1,this);return a};Kd.prototype.Y=function(a){this.Qa&&Sb(this.g.upload,"progress",this.dispatchEvent,!1,this);Kd.xa.Y.call(this,a)};function Ld(){}n(Ld);function Md(a,b){b||(b=0);Z(a,"position","fixed");switch(b){case 1:Z(a,"bottom","0px");Z(a,"left","0px");Z(a,"right","auto");Z(a,"top","auto");break;case 3:Z(a,"bottom","0px");Z(a,"right","0px");Z(a,"left","auto");Z(a,"top","auto");break;case 0:Z(a,"top","0px");Z(a,"left","0px");Z(a,"right","auto");Z(a,"bottom","auto");break;case 2:Z(a,"top","0px"),Z(a,"right","0px"),Z(a,"left","auto"),Z(a,"bottom","auto")}};function Nd(){this.na=Kc.u();Q.d&&(this.Ab=new dc,ec(this.Ab),J("goog").wa(xb),J("chatango").wa(xb));P(window,"pageshow",this.Tb,!1,this);P(window,"orientationchange",this.Sb,!1,this);/ipad|ipod|iphone/gi.test(navigator.appVersion)&&(this.ub=document.documentElement.clientWidth/window.innerWidth,P(document,"gestureend",this.Pb,!1,this));if(this.l=Od()){Lc(this.na,new yc(this.l.src));var a=this.l.id;Q.d&&this.c.info("embedding "+a);this.K=a.replace("cid","").replace("_","");this.l.id+="_";try{this.i=
ma(this.l.innerHTML)}catch(b){throw"Invalid Embed Code";}Pd(this,this.l);this.cb=void 0!=this.i.styles.pm&&1==this.i.styles.pm;(a=this.i.styles.pos)&&hd.u().Ua==id&&(this.i.styles.cv=1);var c=this.i.styles.cv,d=sd(rd.u(),this.i.arch,this.i.styles);Q.d&&console.log("Architecture:",d);"js"==d||"jsonly"==d?(this.Ma=Qd(this,this.l,a,c),this.j=hc.u(),P(this.j,"resizeiframe",this.Vb,!1,this),P(this.j,"browserviewrequest",function(){this.j.send("browserviewresponse",this.L())},!1,this),P(this.j,"buttonexpanded",
this.Mb,!1,this),P(this.j,"buttoncollapsed",this.Lb,!1,this),this.j.ga(this.f.contentWindow,this.l.id,this.Ma,this),P(this.j,"setuserscalable",this.Yb,!1,this),P(this.j,"viewporttoobig",this.ac,!1,this),P(this.j,"settitle",this.$b,!1,this),P(this.j,"connestablished",this.Nb,!1,this)):"flash"==d?Rd(this,this.l):"linkandroidchrome"==d?Sd(this,this.l):"linkandroidff"==d?Td(this,this.l):"linkdesktopchrome"==d&&Ud(this,this.l)}}n(Nd);var Vd=/^cid\d{10,20}$/;g=Nd.prototype;g.c=J("chatango.embed.Embed");
g.$b=function(a){document.title=a.data};function Pd(a,b){a.width=b.style.width;a.height=b.style.height;a.Db=a.width;a.Cb=a.height}g.Vb=function(a){this.width=a.data.width.toString();this.height=a.data.height.toString();Tc(this.f,{width:this.width.replace("px","")+"px",height:this.height.replace("px","")+"px"});this.j.send("resizedone",this.L())};
g.ac=function(){var a=this.i.styles.pos;a||(a=this.i.styles.bpos);var b,c;switch(a){case "tl":break;case "tr":b=document.width;break;case "bl":c=document.height;break;default:c=document.height,b=document.width}window.scrollTo(b,c)};
g.Yb=function(a){switch(a.data){case "disable":Wd(this);a=document.getElementsByTagName("HEAD");if(0==a.length)break;a=a[0];var b=ad(a,function(a){return 1==a.nodeType&&"META"==a.tagName&&"viewport"==a.name});if(0==b.length)this.F=W("META",{name:"viewport",content:"user-scalable=0"}),a.appendChild(this.F),this.D=W("META",{name:"viewport",content:"user-scalable=1"});else{this.D=b[b.length-1];a={};for(var c=this.D.attributes.length,b=0;b<c;b++)a[this.D.attributes[b].nodeName]=this.D.attributes[b].nodeValue;
if(a.content)if(b=a.content.match(/user-scalable\s*=\s*([01yesnotrufal]*)/))if("1"==b[1]||"true"==b[1]||"yes"==b[1])a.content=a.content.replace(/user-scalable\s*=\s*([01yesnotrufal]*)/,"user-scalable=0");else break;else Tc(this.D,{content:a.content+", user-scalable=1"}),a.content+=", user-scalable=0";else a.content="user-scalable=0",this.D.attributes.content="user-scalable=1";this.F=W("META");Tc(this.F,a);$c(this.F,this.D)}break;case "restore":Wd(this)}};
function Wd(a){if(a.F){if(a.D){var b=a.F;b.parentNode&&b.parentNode.insertBefore(a.D,b.nextSibling)}Zc(a.F);a.F=null}}
function Qd(a,b,c,d){1==d&&(a.width=a.i.styles.cvw||65,a.height=a.i.styles.cvh||20);d=Math.floor(256*Math.random()).toString(16)+String((new Date).getTime()).substr(-4,4)+a.K;a.width=String(a.width).split("px")[0];a.height=String(a.height).split("px")[0];var f=-1==String(a.width).indexOf("%")?"px":"";a.f=W("IFRAME",{frameborder:0,width:a.width+f,height:a.height+f,id:d});var e=-1!=navigator.userAgent.indexOf("Mobile")||-1!=navigator.userAgent.indexOf("Android"),f=e?"t":"d";void 0!=a.i.styles.mockgroup&&
(f=e?"MGt":"MGd");a.cb&&(f=e?"PMt":"PMd");a.f.src=Oc()+"/h5/gz/"+nd()+"/i"+f+".html";c?(Z(a.f,"z-index",2147483648),"br"==c?Md(a.f,3):"bl"==c?Md(a.f,1):"tl"==c?Md(a.f,0):"tr"==c&&Md(a.f,2),Yc(a.f)):cd(b)?Yc(a.f):Y(a.f,b);b=Oc()+"/cfg/nc/r.json?"+d;Ld.u();if(c=y)if(c=!B(10))c=b.match(lc)[3]||null,c=(c&&decodeURIComponent(c))!=document.domain;c=c?new Id:new Kd(void 0,void 0);P(c,"success",a.Xb,void 0,a);P(c,["error","timeout","abort"],a.Wb,void 0,a);c.send(b);return d}
g.Xb=function(a){var b=a.currentTarget;a=b.Xa();b=b.Wa();nd()!="r"+a.r&&(a=""+b.substr(b.indexOf("?")+1),b=document.getElementById(a),b.src="about:blank",this.f=W("IFRAME",{frameborder:0,width:b.width,height:b.height,id:a+"_"}),this.f.src="about:blank",$c(this.f,b),this.i.styles.cv?Z(this.f,"display","none"):this.f.contentDocument.write("<html><body><span style='font:11px sans-serif;'>Please clear your browser cache and refresh to see the latest version of Chatango.</span></body></html>"))};
g.Wb=function(){};function Sd(a,b){a.I=W("p",void 0,"This version is not available in your current browser.  ");var c=W("a",{href:"../../../20140527020700/https://play.google.com/store/apps/details?id=com.android.chrome"},"Download Chrome for Android");X(a.I,c);Y(a.I,b)}function Td(a,b){a.I=W("p",void 0,"This version is not available in your current browser.  ");var c=W("a",{href:"../../../20140527020700/https://play.google.com/store/apps/details?id=org.mozilla.firefox"},"Download Firefox for Android");X(a.I,c);Y(a.I,b)}
function Ud(a,b){a.I=W("p",void 0,"This version is not available in your current browser.  ");var c=W("a",{href:"../../../20140527020700/http://google.com/chrome"},"Download Chrome");X(a.I,c);Y(a.I,b)}
function Rd(a,b){var c=a.i.handle,d=a.i.styles,f;f=Mc(a.na).v;var e=Xd(a);a.Ja="http://"+c+"."+f+"/group";a.cb&&(a.Ja="../../../20140527020700/http://st."+f+"/flash/SellersApp.swf");c={src:a.Ja,width:a.width,height:a.height,allowScriptAccess:"always",allowNetworking:"all",type:"application/x-shockwave-flash",allowFullScreen:"true",flashvars:e};if(!("b"in d)||100>d.b)c.wmode="transparent";var d=W("embed"),h;for(h in c)c.hasOwnProperty(h)&&d.setAttribute(h,c[h]);y?"CSS1Compat"==document.compatMode?b.parentElement.insertBefore(d,
b):(Yd(a),a.w.setAttribute("type","application/x-shockwave-flash"),Y(a.w,b)):(Yd(a),X(a.w,d),Y(a.w,b))}
function Yd(a){var b=a.i.styles;Mc(a.na);var c=Xd(a);a.w=W("object",{id:"obj_"+a.K,width:a.width,height:a.height});X(a.w,W("param",{name:"movie",value:a.Ja}));X(a.w,W("param",{name:"AllowScriptAccess",value:"always"}));X(a.w,W("param",{name:"AllowNetworking",value:"all"}));X(a.w,W("param",{name:"AllowFullScreen",value:"true"}));X(a.w,W("param",{name:"flashvars",value:c}));"b"in b&&!(100>b.b)||X(a.w,W("param",{name:"wmode",value:"transparent"}))}
function Xd(a){var b=[],c=a.i.styles,d;b.push("cid="+a.K);"undefined"!=typeof c.a&&b.push("a="+c.a);for(d in c)c.hasOwnProperty(d)&&b.push(d+"="+c[d]);zc(Mc(a.na))==Ic&&(b.push("tagport=20840"),b.push("iconport=1842"),b.push("aimport=6030"),b.push("msnport=2703"));return b.join("&")}function Od(){var a;a=Sc("script",void 0);for(var b=0;b<a.length;b++){var c=a[b].id.match(Vd);if(c)return r(c[0])?document.getElementById(c[0]):c[0]}return null}g.Tb=function(){Q.d&&this.c.info("onPageShow");this.j&&this.j.send("pageshow")};
g.L=function(){var a;a=gd.u().rc;var b={};b.vpwidth=a.L().width;b.vpheight=a.L().height;b.win_innerWidth=window.innerWidth;b.win_innerHeight=window.innerHeight;b.win_innerHeight=window.innerHeight;b.win_outerWidth=window.outerWidth;b.doc_clientWidth=document.documentElement.clientWidth;b.zoom=document.documentElement.clientWidth/window.innerWidth;return b};g.Sb=function(){this.j.send("orientation_change",this.L())};g.Nb=function(){this.j.send("inittitle",document.title)};
g.Mb=function(){this.R||(this.R=W("div",{style:"width:"+this.f.width+"; height:"+this.f.height+"; display:inline-block"}),Y(this.R,this.f));this.j.disconnect();this.Va=!0;Zc(this.f);Yc(this.f);this.j.ga(this.f.contentWindow,this.l.id,this.Ma,this);var a=this.R.style;a.position="relative";y&&!B("8")?(a.zoom="1",a.display="inline"):a.display=z?B("1.9a")?"inline-block":"-moz-inline-box":"inline-block";Z(this.f,"z-index",2147483648);a=this.i.styles.bpos;switch(a){case "tl":a=0;break;case "tr":a=2;break;
case "bl":a=1;break;default:a=3}Z(this.f,"z-index",2147483648);Md(this.f,a)};g.Lb=function(){this.R&&(Z(this.R,"display","none"),this.j.disconnect(),this.Va=!1,Zc(this.f),Y(this.f,this.R),this.j.ga(this.f.contentWindow,this.l.id,this.Ma,this),Z(this.f,"position","static"))};g.Pb=function(){var a=document.documentElement.clientWidth/window.innerWidth;a!=this.ub&&(this.ub=a,a=this.L(),this.j.send("zoomed",a))};this.chatangoembed=Nd;this.chatangoembed.getInstance=this.chatangoembed.u;this.chatangoembed.getInstance()})();


}
/*
     FILE ARCHIVED ON 02:07:00 May 27, 2014 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:24:53 Nov 17, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.684
  exclusion.robots: 0.041
  exclusion.robots.policy: 0.01
  esindex: 0.011
  cdx.remote: 9.998
  LoadShardBlock: 350.73 (6)
  PetaboxLoader3.datanode: 226.453 (8)
  load_resource: 313.762 (2)
  PetaboxLoader3.resolve: 203.055 (2)
*/